# Non-Jekyll Configuration
twitter_username: Elad
github_username: SaladFork
url: "https://blog.eladshahar.com"

# Handling Reading
exclude: [run.rb]
encoding: utf-8

# Outputting
permalink: none

#Conversion
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  use_coderay: true
  syntax_highlighter: coderay
